### ISSUE TITLE
Need 

### ISSUE THREAD

**Issue by galt** [HumanCellAtlas/fusillade#257]
The instructions here say I need to request a service account and RSA key-pair 

https://github.com/HumanCellAtlas/ingest-core/blob/master/docs/primary-submission-walkthrough.md
QUOTE
Set-up a service account
You must have a valid token identifying your service in order to use the Ingest API.

The DCP uses Google service accounts for authenticating service-to-service requests. 
To request a service account and associated RSA key-pair, create an issue in Fusillade, the DCP's auth service.

Use this library with your key file to sign a JWT token identifying your service.

-------
Questions:
 Where is my key file for JWT Token?
I am a total beginner on HCA from UCSC. Thanks.

**Comment by galt** [comment]
Unfortunately I have used galt@soe.ucsc.edu in most places,
but currently gbarber@ucsc.edu is used on https://ui.ingest.staging.data.humancellatlas.org/home.
My github /galt is just also on galt@soe.ucsc.edu

**Comment by galt** [comment]
Looks like I am going to use gbarber@ucsc.edu.

**Comment by galt** [comment]
Is there any progress on this for gbarber@ucsc.edu?

**Comment by Bento007** [comment]
[login](https://auth.data.humancellatlas.org/login?state=ABC&redirect_uri=https://auth.data.humancellatlas.org/echo)  and copy the access_token. This is your JWT, that must be provided in the request authorization header.

**Comment by galt** [comment]
So I have been successful getting the access_token from that login url you gave me above, using a browser, logging in, getting redirected to echo, then getting my token from the json response. But the token only lasts 24 hours. There should be a programmatic way to fetch an up-to-date JWT token as well. What do I need to do that?

**Comment by galt** [comment]
Any help here would be greatly appreciated. Thanks!

**Comment by galt** [comment]
from hca.dss import DSSClient
client = DSSClient()
session = client.get_authenticated_session()
DCP_TOKEN = session.token["access_token"]
print(f"DCP_TOKEN={DCP_TOKEN}")

Got the code from Trent.

It currently requires
hca dss login
but they want to either change dss to dcp,
or just drop it to simply have
hca login

Thanks very much!
