### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/fusillade#26]
# User stories
* As a user, I would like to revoke a token after a sessions, to prevent unauthorized used.
* As an admin, I would like to revoke a user's token, to prevent unauthorized use.

# Definition of Done
* store JWT in clouddirectory and attach to user. When logout is sent ,revoke credentials.
* Admins and users must be able to revoke access for a token.

# Resources
https://auth0.com/docs/tokens/refresh-token/current

Tokens should have a short life span since they cannot be revoked https://auth0.com/docs/tokens/guides/revoke-tokens

For a single page application this sounds like the prefered mehod.
https://auth0.com/docs/api-auth/tutorials/silent-authentication

**Comment by Bento007** [comment]
store JWT in clouddirectory and attach to user. When logout is sent ,revoke credentials. verify

**Comment by Bento007** [comment]
Due to the nature of JWT being self contained authentication tokens there is no mechanism to invalidate a specific JWT. However we do have options: 
1. Return a JWT with a refresh token. The JWT will have a very short life time of a few seconds or minutes before a new token will need to be retrieved. The refresh token will be used to retrieve the new token. When the user wants to logout, the refresh token will be revoked, and new tokens cannot be retrieved using the old refresh token. However any access_tokens retrieved prior to revoking the refresh token will remain active until they expire.
2. We can add a data base to track tokens that are active i.e. not expired and “logged out”. If this access token is used, it will not be authorized, and will be removed from the database once the token has expired. This will require adding a database to manage the logged out tokens.

**Comment by stahiri** [comment]
@adrazhi any thoughts on the options Trent laid out above?

**Comment by Bento007** [comment]
This blog does a good job of describing the client side flow for using a JWT securely using short lived tokens with a revokable refresh token. https://blog.hasura.io/best-practices-of-using-jwt-with-graphql/#login

**Comment by Bento007** [comment]
Using the revoke endpoint in auth0 will revoke all refresh tokens give to that user by auth0 not just the one provide in the request. We should make a complete logout optional. 
```python
def logout(revoke=False)
    """ Logout the user, if revoke is true, all refresh tokens issues 
         to that user for the hca will be revoked."""
    pass
```

**Comment by Bento007** [comment]
We should also make it clear when logging in that a refresh token is not required and should only be used on secure machines.

**Comment by Bento007** [comment]
For auth0 using OIDC implicit grants should be used for single page applications (SPA)

**Comment by Bento007** [comment]
Admins can revoke access token by logging into the Auth0 console, selecting the user, and revoking their refresh tokens.

**Comment by Bento007** [comment]
fixed by https://github.com/HumanCellAtlas/fusillade/pull/289
