### ISSUE TITLE
Too many redirects error in authorize endpoint

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/fusillade#282]
## Software version
integration (not sure if I've seen this in other env)

## Expected behavior
Redirect to OAuth page

## Actual behavior
Too many redirects error
## Steps to reproduce the behavior
- Login in Ingest UI 
https://ui.ingest.dev.data.humancellatlas.org/login
(the UI does a GET request to 
https://auth.integration.data.humancellatlas.org/oauth/authorize?redirect_uri=http://localhost:4200/callback)

**Comment by chmreid** [comment]
@Bento007 Sounds like `redirect_uri` was set to localhost for local testing and wasn't updated

**Comment by aaclan-ebi** [comment]
Sorry, I made a mistake when I created the ticket. I was running it locally when i copied the redirect url. The redirect url is set based on the env where the UI is running.

Here's the actual url in integration
https://auth.integration.data.humancellatlas.org/oauth/authorize?redirect_uri=https://ui.ingest.integration.data.humancellatlas.org/callback

**Comment by Bento007** [comment]
Not fixed
