### ISSUE TITLE
Fusillade Configure

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/fusillade#33]
# User Story
* As a fusillade admin, I want to know how to setup Fusillade with an OIDC provider, so I can add and remove providers as needed.
* As a fusillade admin, I would like to define default permissions assigned to all new users, to simplify the enrollment process of users.
* As a fusillade developer, I need to provide a default admin setup when deploying fusillade, to configure all other users and add additional admins.
 * As a fusillade operator, I want to modify the configuration of fusillade in a single file.

# Definition of Done
* All of the above stories are complete
* all configuration parameters are stored in a single file.

**Comment by kozbo** [comment]
@Bento007 Is this done?

**Comment by Bento007** [comment]
complete
