### ISSUE TITLE
Health and status checks

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/fusillade#35]
# User Story
* Health - monitoring and alerting facilities in accordance with DCP production practices (GA tech requirements)
* As a DCP operator, I need to know the status of Fusillade periodically, this will allow me to monitor and take action in the event service to Fusillade is disrupted.
  * Define the health check endpoint which returns 200 when the system is operational and 500 when the system has issues.
  * Implement period health check on AWS cloud directory, auth0, AWS iam policy evaluation service

# DoD
- [x] define /status API endpoint
- [ ] check status of Auth0
- [ ] check status of cloud directory
- [ ] check status of lambda
- [ ] check status of API gateway
- [ ] check status of AWS policy evaluation engine

**Comment by mweiden** [comment]
Superset of https://github.com/HumanCellAtlas/fusillade/issues/74

**Comment by mweiden** [comment]
Fulfills https://github.com/HumanCellAtlas/fusillade/issues/76
