### ISSUE TITLE
Use Evaluate on All endpoints

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/fusillade#46]
All Fusillade endpoints should use its own evaluation engine to determine if a user has permissions to perform an action.

# DoD

- [x] create google service credential to run the test automation
- [x] Modify endpoints to read the bearer token from the header
- [x] add evaluate to roles endpoints
- [x] add evaluate to evaluate endpoint
- [x] add evaluate to users 
- [x] add evaluate to groups

**Comment by jharini** [comment]
Added evaluate to users and groups endpoints
