### ISSUE TITLE
Log all API requests

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/fusillade#51]
# User Story
As an operator, I need to maintain a record of api requests for auditing and security reasons.

# DoD
Log all api requests
Log when a user is created
Log when a group is created
Log when a role is created

**Comment by Bento007** [comment]
this is partially complete but needs to be validated

**Comment by mweiden** [comment]
Note that this partially overlaps with https://github.com/HumanCellAtlas/fusillade/issues/79

**Comment by Bento007** [comment]
Done
