### ISSUE TITLE
Components provide a “health check” HTTPS endpoint

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/fusillade#74]
Each component must provide a `/health` HTTPS endpoint that should, at the very minimum respond with status 200 if the service is up and healthy.  A response body may be present that provides additional information, that if present must be a JSON object.

- [ ] Metadata /health point returns 200
- [x] Ingest /health point returns 200
- [x] Upload /health point returns 200
- [x] DSS /health point returns 200
- [x] Pipelines /health point returns 200
- [x] Matrix /health point returns 200
- [ ] Azul /health point returns 200
- [x] Browser /health point returns 200
- [x] Portal /health point returns 200
- [x] Logging /health point returns 200
- [x] Metrics /health point returns 200

**Comment by mweiden** [comment]
Fulfilled when https://github.com/HumanCellAtlas/fusillade/issues/35 is complete.
