### ISSUE TITLE
Alerts are sent to dev/ops team for a component when it is down/unhealthy

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/fusillade#77]
As a developer/operator of the DCP
when a component is down or unhealthy
I should receive an alert

Our current alert mechanism is to send messages to an appropriate Slack channel.
I believe @mweiden's status dashboard does this.  You just need to tell it where to look.

**Comment by mweiden** [comment]
Yes, we have configuration for this, though it's in the `dcp-monitoring` repo. Instructions here: https://github.com/HumanCellAtlas/dcp-monitoring#configure-an-alert

**Comment by mweiden** [comment]
Whomever picks up this ticket, feel free to put time on my calendar to work on this together.

**Comment by stahiri** [comment]
@Bento007 I'm updating the release in this from GA to Q3 given your Q3 Sprint 1 milestone

**Comment by mweiden** [comment]
This is complete https://github.com/HumanCellAtlas/dcp-monitoring/blob/master/terraform/modules/env-health-checks/auth.tf
