### ISSUE TITLE
A dashboard of metrics is available for ops to monitor the aggregate activity of each component

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/fusillade#80]
As a DCP component ops person,
I want to see a dashboard of metrics for my component,
so I can tell how my component has performed recently, and tell if it:
- seems unhealthy
- is being unintentionally misused
- is under malicious attack

Dashboards should include, among other key metrics, HTTP error rates for API endpoints.
It is also wise to graph API response latencies.

- [ ] Ingest
- [x] Upload
- [x] Data Store
- [x] Analysis
- [x] Matrix
- [x] Azul
- [ ] Portal
- [x] Logs

**Comment by Bento007** [comment]
This is complete for the dev environment. It still needs to be deployed for integration, staging, and production.

**Comment by mweiden** [comment]
I've deployed these to the other environments.
