### ISSUE TITLE
Operator Documentation (RunBooks)

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/fusillade#81]
Internal.

Runbook should detail how to deploy the component.
Runbook should detail how to roll-back a deployment.
Runbook should provide guidance on how to diagnose / resolve common problems.

Create your RunBook on allspark.dev.data.humancellatlas.org
Put a link to it in this page: https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/wikis/home

Examples:

https://github.com/HumanCellAtlas/ingest-central/blob/master/release-manager-playbook.md

[SOP: Releasing new Versions of DCP Software](https://docs.google.com/document/d/1HbSWuIABaavaHpCwaO0peA_uwTW5wBCdRnYoz7ZVQuQ/edit?ts=5b0d7550#heading=h.yw6cvy5vlmbu)

[Playbook template in doc form](https://docs.google.com/document/d/1EPcN1tEIwMuzRXj8JPARd-Vgnc3sXJvwQOEcVWkVaYc/edit)

**Comment by Bento007** [comment]
WIP https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/wikis/Fusillade%20Runbook

**Comment by Bento007** [comment]
Still partially complete

**Comment by stahiri** [comment]
@Bento007 it looks like the Fusillade runbook has been published to the wiki (https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/wikis/Fusillade%20Runbook) so I believe this ticket can be closed. Can you confirm and close? Thanks!

**Comment by Bento007** [comment]
complete
