### ISSUE TITLE
Detect secrets that have leaked into source code

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/fusillade#87]
As a dcp developer
I want to run static analysis tools on my code
to help not ship code with gaping security holes in it.

There has been talk of running `trufflehog`, a tool to find embedded secrets in code before it is pushed.
The DevSecOps team needs to decide what static analysis tools to encourage/mandate.
Then we update the tickets in the component repos with these instructions.

**Comment by hariniczi** [comment]
@DailyDreaming Can you help me setup trufflehog for Fusillade?

**Comment by stahiri** [comment]
Quick update: The DevSecOps team is actively working to see if we can implement Trufflehog from a central location as a check on each PR. This ticket will be closed upon confirmation that this is possible and work is completed. In the meantime, I'm assigning this ticket to the Q3 release.

@Bento007 - could you advise if trufflehog has been set up on fusillade's repo individually?

**Comment by Bento007** [comment]
@stahiri trufflehog has been configured to run in gitlab for fusillade.

**Comment by Bento007** [comment]
could we add it to run on all HCA repos using a cron job in https://github.com/HumanCellAtlas/dcp/blob/master/.gitlab-ci.yml

**Comment by stahiri** [comment]
Closing this ticket as the required activity has been completed.
