### ISSUE TITLE
Jsonify `/echo` endpoint

### ISSUE THREAD

**Issue by amarjandu** [HumanCellAtlas/fusillade#89]
Currently it appears that the redirection of `https://auth.dev.data.humancellatlas.org/authorize?response_type=code&client_id=qtMgNk9fqVeclLtZl6WkbdJ59dP3WeAt&redirect_uri=https%3A%2F%2Fauth.dev.data.humancellatlas.org%2Fecho&scope=openid+email+offline_access&state=B1bdmsJgVk0r9HhkG4xMLsdvde16G5&access_type=offline` returns a python dictionary object, the response header indicates that the content-type should be `application-json`; if this could be changed it would allow browsers to present the code needed for non-interactive logins in a clean + user friendly way.

**Comment by Bento007** [comment]
fixed
