### ISSUE TITLE
Create User Endpoints

### ISSUE THREAD

**Issue by brianraymor** [HumanCellAtlas/fusillade#98]
@hariniczi commented on [Mon Apr 29 2019](https://github.com/HumanCellAtlas/dcp/issues/387)

* users
* users/<userId>
* users/<userId>/<enable/disable>

---

@brianraymor commented on [Tue Apr 30 2019](https://github.com/HumanCellAtlas/dcp/issues/387#issuecomment-488025110)

@hariniczi - Why was this issue created in the top-level _dcp_ repo? Is there a more appropriate repo that it can be moved to?

**Comment by brianraymor** [comment]
Moved to _fusillade_ per @mweiden.

**Comment by jharini** [comment]
Reassigning to myself and closing it
